config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  get 'homes/about' => 'homes#top'
  get 'prints/index' => 'prints#index'
  get 'chats/edit' => 'chats#edit'
  post 'chats/create' => 'chats#create'
  get 'chats/index' => 'chats#index'
   
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chat.rb
class Chat < ApplicationRecord
    belongs_to :user
end

app/models/print.rb
class Print < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :prints
  has_many :chats
end

app/controllers/api/chats_controller.rb
class ChatsController < GptController

    def index
    end
  
    # 入力したテキストに対して返答
    def search
      @query = params[:query]
  
      response = @client.chat(
        parameters: {
            model: "gpt-3.5-turbo",
            messages: [{ role: "user", content: @query }],
           
        })
  
      @chats = response.dig("choices", 0, "message", "content")
    end
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    def after_sign_in_path_for(resource)
        homes_about_path
    end

    def after_sign_out_path_for(resource)
        homes_about_path
    end

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    end
end

app/controllers/chats_controller.rb
class ChatsController < GptController

    def index
      # @question1 = :question1
      # @question2 = :question2
      # @question3 = :question3
      # @question4 = :question4
      # @question5 = :question5
      # @question6 = :question6
      # @question = :question
      # html = File.read("#{Rails.root}/app/views/chats/index.html.erb")
      # kit = PDFKit.new(html, :page_size => 'A4')
      # # kit.stylesheets << "#{Rails.root}/public/styles.css"
      # kit.to_file("#{Rails.root}/public/print.pdf")
      # send_data kit.to_pdf, filename: 'print.pdf', type: 'application/pdf'
    end

    def edit
      render :edit, layout: 'application'
    end
  
    def search
      @query = params[:query]
  
      response = @client.chat(
        parameters: {
            model: "gpt-3.5-turbo",
            messages: [{ role: "user", content: @query }],
        })
  
      @chats = response.dig("choices", 0, "message", "content")
      put @chats
      render :edit, layout: 'application'
    end

    def create
      @chat = Chat.new()
      @chat.content = params[:query]
      @chat.user_id = current_user.id
      @chat.save

      @res = []
      @res.push({role: "system", content: "私は教員です。私の問題作成を手伝ってください。私が送信する内容に沿った問題を提示してください。" })
      @res.push({role: "system", content: "問題の形式は" + params[:question] + "で出力してください" })

      Chat.all.each do |c|
        @res.push({ role: 'user', content: c.content })
      end

      response = @client.chat(
        parameters: {
          model: 'gpt-3.5-turbo',
          messages: @res
        }
      )

      @chats = response.dig('choices', 0, 'message', "content")
      render :edit, layout: 'application'
    end
  end

app/controllers/gpt_controller.rb
class GptController < ActionController::Base
require "openai"
require 'dotenv'
Dotenv.load

  before_action :set_common_variable

  private
  HACKU_API_KEY = ENV["API_KEY"]

  # APIキーの設定
  def set_common_variable
    @client = OpenAI::Client.new(access_token: HACKU_API_KEY)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    # @user = current_user
  end

  def about
  end
end

app/controllers/prints_controller.rb
class PrintsController < ApplicationController
    def index
        @prints=Print.all
    end
    def new
    end

    def create
        @print = Print.new(print_params)
        @print.user_id = current_user.id
        @print.save
        redirect_to ""
    end

    private

    def print_params
        params.require(:print.permit)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @print = Print.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/prints_helper.rb
module PrintsHelper
end

app/views/chats/chat.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>B5エディタ</title>
    <style>
        @page {
            size: B5;
        }
        body {
            margin: 0;
            padding: 0;
        }
        .editor {
            width: 100%;
            height: 100vh;
            padding: 20px;
            box-sizing: border-box;
            font-size: 16px;
            line-height: 1.5;
        }
        .header{
            width: 100%;
            height: 100px;
            border: solid;
        }
    </style>
</head>
<body>
    <div class="editor" contenteditable="true" id="editor">
        <div class="header"></div>
        <input type="text" id="title" value="タイトル">
    </div>
    <%= link_to "PDF出力", chats_index_path, method: :get %>

</body>
</html>

app/views/chats/edit.html.erb
<%= form_with(url: chats_create_path , method: :post, data: { turbo: false }) do |form| %>
<p>問題の傾向を選択してください<br>
</p>
<%= form.select :question, [["四択問題", "四択問題"], ["記述問題", "記述問題"], ["穴埋め問題", "穴埋め問題"], ["計算問題", "計算問題"]], include_blank: "選択して下さい" %>
<p>AIに聞く文章を書く欄<br>
</p>
<%= form.text_field :query, size: 55%>
<%= form.submit "検索" %>
<% end %>

<p>AIが作った問題<br>
<div class="input-container">
  <textarea id="copyText" cols="50" rows="5"> <%= @chats %> </textarea>
  <button onclick="copyToClipboard(this)">
  Copy Text
  </button>
</div>
<p class="p">プリント作成</p>
<!--
# <div class="print">
#   <%= form_with(url: chats_index_path , method: :get) do |form| %>
#   <div class="name">
#     <p>名前
#     <%= form.text_field :question, size:55%><br>
#     </p>
#   </div>
#   <div class="top">
#     <%= form.text_area :question1, cols:100, rows:7%><br>
#   </div>
#   <div class="answer">
#     <%= form.text_area :question2, cols:50, rows:5%><br>
#   </div>
#   <%= form.text_area :question3, cols:100, rows:7%><br>
#   <div class="answer">
#     <%= form.text_area :question4, cols:50, rows:5%><br>
#   </div>
#     <%= form.text_area :question5, cols:100, rows:7%><br>
#   <div class="answer">
#     <%= form.text_area :question6, cols:50, rows:5%><br>
#   </div>
# </div>-->
<div style="display: flex;
        justify-content: center;">
<iframe src="/chat.html" width="60%" style="aspect-ratio: 176 / 250;"></iframe>
</div>
<div class="pdf" >
  <%= link_to "編集画面", chats_index_path, method: :get%>
</div>
<% end %>

app/views/chats/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>B5エディタ</title>
    <style>
      @page {
          size: B5;
      }
      .question .answer {
        border: solid;
      }
      .print {
        width: 100%;
        aspect-ratio: 297 / 420;
      }
      .name {
        width: 40%;
        height: 70px;
        border-bottom: solid;
        margin: auto;
        margin-right: 0;
        margin-bottom: 30px;
      }
      .question {
        width: 55%;
        height: 100px;
        border-bottom: solid;
      }
      .answer {
        width: 30%;
        height: 70px;
        border-bottom: solid;
        margin-top: 60px;
        margin-bottom: 25px;
        margin-left: auto;
        margin-right: 0;
      }
    </style>
  </head>
  <body >
    <div class="print">
      <div class="name" contentEditable="true">名前 <br><br></div>
      <div class="question" contentEditable="true">
        <h3 >問題: <br><br></h3>
      </div>
      <div class="answer" contentEditable="true">解答:<br><br> </div>
      <div class="question"contentEditable="true">
        <h3 >問題:<br><br></h3>
      </div>
      <div class="answer" contentEditable="true">解答:<br><br> </div>
      <div class="question" contentEditable="true">
        <h3 >問題:<br><br></h3>
      </div>
      <div class="answer" contentEditable="true">解答:<br><br> </div>
    </div>
  </body>
</html>

app/views/chats/search.html.erb
<div class="top">
<p>AIが作った問題<br>

<div class="input-container">
<!-- <input type="text" id="copyText" placeholder="入力してください。" /> -->
<textarea id="copyText" cols="50" rows="5"> <%= @chats %> </textarea>
<button onclick="copyToClipboard(this)">
  Copy Text
</button>

app/views/homes/about.html.erb
<h1>Homes#about</h1>
<p>Find me in app/views/homes/about.html.erb</p>

app/views/homes/top.html.erb
<h1>教材作成アプリへようこそ！</h1>
<% if user_signed_in? %>
<%= link_to "新規作成！", chats_edit_path, class: "editbotton" %>
<% else %>
<p>使用の前にログインをお願いします</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CreateStudyTool</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script>
  async function copyToClipboard(obj) {
    const element = obj.previousElementSibling;
    // クリップボードAPIが使え、且つ、値が空でない時
    if (navigator.clipboard && !element.value == false) {
      await navigator.clipboard.writeText(element.value);
      alert("コピーされました！");
    } else {
      alert("コピーされませんでした！");
    }
  }
  </script>
  <meta name="turbolinks-visit-control" content="reload">
  </head>

  <body>
    <header>
      <% if user_signed_in? %>
        <li>
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
        </li>
      <% else %>
        <li>
          <%= link_to "新規登録", new_user_registration_path %>
        </li>
        <li>
          <%= link_to "ログイン", new_user_session_path %>
        </li>
      <% end %>
    </header>
    <%= yield %>
  </body>
</html>

app/views/prints/index.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8" />
  <title>新規作成</title>
  <link rel="stylesheet" href="style.css" />
</head>
<body>
  <header class="header">
    <div class="nav">

    <input id="drawer_input" class="drawer_hidden" type="checkbox">

    <label for="drawer_input" class="drawer_open"><span></span></label>

    <nav class="nav_content">
      <ul class="nav_list">
        <li class="nav_item"><a href="">1</a></li>
        <li class="nav_item"><a href="">2</a></li>
        <li class="nav_item"><a href="">3</a></li>
      </ul>
    </nav>
  
    </div>
    <select name="subject" class="subject">
      <option value="国語">国語</option>
      <option value="数学">数学</option>
    </select>
    <div class="search">
      <input type="text" id="search" size="20" />
      <input
        class="button"
        type="button"
        value="検索"
        onclick="alert_search()"
      />
      <script>
        function alert_search() {
        var message = document.getElementById("search").value;
        alert(message);
        }
      </script>
    </div>
    <div class="new">
      <input
        class="button"
        type="button"
        onclick="location.href=`http://localhost:3000/chats/edit`"
        value="新規作成"
      />
    </div>
  </header>
  <main>
<div class="posts-container">
  <% @prints.each do |t| %>
    <div class="temprete">
    <%= t.status %>
    </div>
  <% end %>
</div>
    <%# <div class="image-list">
      <img class="template" src="https://www.shoshinsha-design.com/wp-content/uploads/2020/05/noimage-760x460.png" alt="">
      <img class="template" src="https://www.shoshinsha-design.com/wp-content/uploads/2020/05/noimage-760x460.png" alt="">
      <img class="template" src="https://www.shoshinsha-design.com/wp-content/uploads/2020/05/noimage-760x460.png" alt="">
      <img class="template" src="https://www.shoshinsha-design.com/wp-content/uploads/2020/05/noimage-760x460.png" alt="">
      <img class="template" src="https://www.shoshinsha-design.com/wp-content/uploads/2020/05/noimage-760x460.png" alt="">
      <img class="template" src="https://www.shoshinsha-design.com/wp-content/uploads/2020/05/noimage-760x460.png" alt="">
      <img class="template" src="https://www.shoshinsha-design.com/wp-content/uploads/2020/05/noimage-760x460.png" alt="">
      <img class="template" src="https://www.shoshinsha-design.com/wp-content/uploads/2020/05/noimage-760x460.png" alt="">
      <img class="template" src="https://www.shoshinsha-design.com/wp-content/uploads/2020/05/noimage-760x460.png" alt="">
      <img class="template" src="https://www.shoshinsha-design.com/wp-content/uploads/2020/05/noimage-760x460.png" alt="">
      <img class="template" src="https://www.shoshinsha-design.com/wp-content/uploads/2020/05/noimage-760x460.png" alt="">
      <img class="template" src="https://www.shoshinsha-design.com/wp-content/uploads/2020/05/noimage-760x460.png" alt="">
      <img class="template" src="https://www.shoshinsha-design.com/wp-content/uploads/2020/05/noimage-760x460.png" alt="">
      <img class="template" src="https://www.shoshinsha-design.com/wp-content/uploads/2020/05/noimage-760x460.png" alt="">
      <img class="template" src="https://www.shoshinsha-design.com/wp-content/uploads/2020/05/noimage-760x460.png" alt="">
      <img class="template" src="https://www.shoshinsha-design.com/wp-content/uploads/2020/05/noimage-760x460.png" alt="">
      <img class="template" src="https://www.shoshinsha-design.com/wp-content/uploads/2020/05/noimage-760x460.png" alt="">
      <img class="template" src="https://www.shoshinsha-design.com/wp-content/uploads/2020/05/noimage-760x460.png" alt="">
      <img class="template" src="https://www.shoshinsha-design.com/wp-content/uploads/2020/05/noimage-760x460.png" alt="">
      <img class="template" src="https://www.shoshinsha-design.com/wp-content/uploads/2020/05/noimage-760x460.png" alt="">
      <img class="template" src="https://www.shoshinsha-design.com/wp-content/uploads/2020/05/noimage-760x460.png" alt="">
      <img class="template" src="https://www.shoshinsha-design.com/wp-content/uploads/2020/05/noimage-760x460.png" alt="">
      <img class="template" src="https://www.shoshinsha-design.com/wp-content/uploads/2020/05/noimage-760x460.png" alt="">
      <img class="template" src="https://www.shoshinsha-design.com/wp-content/uploads/2020/05/noimage-760x460.png" alt="">
      <img class="template" src="https://www.shoshinsha-design.com/wp-content/uploads/2020/05/noimage-760x460.png" alt="">
      <img class="template" src="https://www.shoshinsha-design.com/wp-content/uploads/2020/05/noimage-760x460.png" alt="">
      <img class="template" src="https://www.shoshinsha-design.com/wp-content/uploads/2020/05/noimage-760x460.png" alt="">
      <img class="template" src="https://www.shoshinsha-design.com/wp-content/uploads/2020/05/noimage-760x460.png" alt="">
      <img class="template" src="https://www.shoshinsha-design.com/wp-content/uploads/2020/05/noimage-760x460.png" alt="">
      <img class="template" src="https://www.shoshinsha-design.com/wp-content/uploads/2020/05/noimage-760x460.png" alt="">
      <img class="template" src="https://www.shoshinsha-design.com/wp-content/uploads/2020/05/noimage-760x460.png" alt="">
      <img class="template" src="https://www.shoshinsha-design.com/wp-content/uploads/2020/05/noimage-760x460.png" alt="">
      <img class="template" src="https://www.shoshinsha-design.com/wp-content/uploads/2020/05/noimage-760x460.png" alt="">
      <img class="template" src="https://www.shoshinsha-design.com/wp-content/uploads/2020/05/noimage-760x460.png" alt="">
    </div> %>
  </main>
</body>
</html>